dist: xenial
language: java
sudo: true
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  - openjdk11

env:
  global:
  - GRADLE_OPTS=-Dorg.gradle.daemon=false

install: /bin/true

script:
  - sudo sysctl -w net.ipv4.ping_group_range="0 9999"
  - sudo sysctl net.ipv6.conf.all.disable_ipv6=0
  - sudo sysctl net.ipv6.conf.default.disable_ipv6=0
  - cat /proc/net/if_inet6
  - ping6 -c 2 2001:4860:4860::8888
  - ./gradlew build --info
