version: 2.1

jobs:
  build:
    machine: true # executor type
    resource_class: brettwooldridge/ubuntu

    steps:
      # Commands run in a Linux virtual machine environment
      - checkout
      - run: ./gradlew clean build
